import Head from "next/head";

import { Inter } from "@next/font/google";
import PortfolioNavBar from "../components/navbar";
import HeroSection from "@/components/hero";
import Skills from "../components/skills";
import AboutMe from "@/components/aboutme";

// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PortfolioNavBar />
      <HeroSection />
      <Skills />
      <AboutMe />
    </>
  );
}
